name: Terraform CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terraform-check:
    name: Terraform Check
    runs-on: ubuntu-latest
    environment: terraform-beanstalk-secrets
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.0
    
    - name: Check Format
      run: |
        cd terraform
        terraform fmt -check
    
    - name: Initialize
      run: |
        cd terraform
        terraform init -backend=false
    
    - name: Validate
      run: |
        cd terraform
        terraform validate
    
    - name: Test Plan
      run: |
        cd terraform
        terraform plan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      continue-on-error: true

# Required GitHub Environment: terraform-beanstalk-secrets
# Environment Secrets:
# AWS_ACCESS_KEY_ID - Your AWS Access Key ID
# AWS_SECRET_ACCESS_KEY - Your AWS Secret Access Key  
# AWS_REGION - AWS region (e.g., eu-north-1)
